#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#

heat_template_version: 2013-05-23

description: All-in-one Webmail stack

parameters:
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string

  mysql_password:
    description: Mysql password
    label: Mysql password
    type: string
    default: changeme

  postfix_admin_pass:
    description: postfixadmin password
    label: postfixadmin password
    type: string
    default: changeme

  mail_domain:
    description: mail domain
    label: mail domain
    type: string
    default: exemple.com

  flavor_name:
    default: n2.cw.standard-1
    description: Flavor to use for the deployed instance
    type: string
    label: Openstack Flavor
    constraints:
      - allowed_values:
        - t1.cw.tiny
        - s1.cw.small-1
        - n2.cw.standard-1
        - n2.cw.standard-2
        - n2.cw.standard-4
        - n2.cw.standard-8
        - n2.cw.standard-16
        - n2.cw.highmem-2
        - n2.cw.highmem-4
        - n2.cw.highmem-8
        - n2.cw.highmem-16

resources:
  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.250.0/24
      allocation_pools:
        - { start: 10.0.250.100, end: 10.0.250.199 }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, protocol: TCP, port_range_min: 443, port_range_max: 443 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: 3ada4d87-0aee-4f77-b10a-b7a9d730b20b
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                  cat << EOF > /etc/ansible/mail-vars.yml
                  ---
                  mysql_mailuser_password: '$mysql_password$'
                  password_admin: '$postfix_admin_pass$'
                  EOF

                  if [ "$mail_domain$" == "exemple.com" ] ;
                  then
                  cat << EOF >> /etc/ansible/mail-vars.yml
                  mail_domain: 'ip-$(echo $floating_ip$ | tr "." "-").rev.cloudwatt.com'
                  email_admin: 'admin@ip-$(echo $floating_ip$ | tr "." "-").rev.cloudwatt.com'
                  EOF
                  echo "127.0.0.1  ip-$(echo $floating_ip$ | tr "." "-").rev.cloudwatt.com" >>/etc/hosts
                  echo "ip-$(echo $floating_ip$ | tr "." "-").rev.cloudwatt.com" >>/etc/hostname
                  else
                  cat << EOF >> /etc/ansible/mail-vars.yml
                  mail_domain: '$mail_domain$'
                  email_admin: 'admin@$mail_domain$'
                  EOF
                  echo "127.0.0.1  $mail_domain$" >>/etc/hosts
                  echo "$mail_domain$" >>/etc/hostname
                  fi
                  ansible-playbook /root/mail-install/mail-install.yml -e @/etc/ansible/mail-vars.yml

          params:
                $floating_ip$: { get_attr: [floating_ip, floating_ip_address] }
                $mysql_password$: { get_param: mysql_password }
                $postfix_admin_pass$: { get_param: postfix_admin_pass }
                $mail_domain$: { get_param: mail_domain }


  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

outputs:
  floating_ip_url:
    description: Webmail URL
    value:
      str_replace:
        template: https://ip-$public_dns.rev.cloudwatt.com/
        params:
          $public_dns: {"Fn::Replace": [ {'.': '-'}, get_attr: [floating_ip, floating_ip_address]]}
