heat_template_version: 2013-05-23


description: All-in-one Graylog stack


parameters:
  keypair_name:
    label: SSH Keypair
    description: Keypair to inject in instance
    type: string

  password:
    label: Password
    description: Graylog admin password
    type: string
    hidden: true
    constraints:
      - length: { min: 6, max: 96 }
        description: Password must be between 6 and 96 characters

  flavor_name:
    label: Instance Type (Flavor)
    description: Flavor to use for the deployed instance
    type: string
    default: n2.cw.standard-1
    constraints:
      - allowed_values:
          - t1.cw.tiny
          - s1.cw.small-1
          - n2.cw.standard-1
          - n2.cw.standard-2
          - n2.cw.standard-4
          - n2.cw.standard-8
          - n2.cw.standard-12
          - n2.cw.standard-16
          - n2.cw.highmem-2
          - n2.cw.highmem-4
          - n2.cw.highmem-8
          - n2.cw.highmem-12

resources:
  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.1.0/24
      allocation_pools:
        - { start: 10.0.1.100, end: 10.0.1.199 }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 9000, port_range_max: 9000 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

  application_secret:
    type: OS::Heat::RandomString
    properties:
      length: 96
      salt: String

  secret_injection:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            PASSWORD_SHA2="$(echo -n PASSWORD | shasum -a 256 | cut -d" " -f1)"
            sudo sed -i "s/root_password_sha2 =/root_password_sha2 = $PASSWORD_SHA2/g"               /etc/graylog/server/server.conf
            sudo sed -i "s/password_secret =/password_secret = APPLICATION_SECRET/g"                 /etc/graylog/server/server.conf
            sudo sed -i 's/application.secret=""/application.secret="APPLICATION_SECRET"/g'          /etc/graylog/web/web.conf
            sudo service graylog-web restart
            sudo service graylog-server restart
          params:
            PASSWORD: { get_param: password }
            APPLICATION_SECRET: { get_resource: application_secret }

  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: secret_injection }

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: e401827f-d18e-41d8-93d0-bc1938fa1316
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }
      user_data_format: RAW
      user_data:
        get_resource: server_init

outputs:
  floating_ip_url:
    description: Graylog URL
    value:
      str_replace:
        template: http://$floating_ip:9000/
        params:
          $floating_ip: { get_attr: [floating_ip, floating_ip_address] }

  graylog_secret:
    description: Graylog application.secret
    value:
      str_replace:
        template: APPLICATION_SECRET
        params:
          APPLICATION_SECRET: { get_resource: application_secret }
