#
##
### Written by the CAT team
##
#
heat_template_version: 2013-05-23

description: MyCloudManager for Cloudwatt


parameters:
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string

  os_username:
    description: OpenStack Username
    label: OpenStack Username
    type: string

  os_password:
    description: OpenStack Password
    label: OpenStack Password
    type: string
    hidden: true

  os_tenant:
    description: OpenStack Tenant Name
    label: OpenStack Tenant Name
    type: string

  os_auth:
    description: OpenStack Auth URL
    default: https://identity.fr1.cloudwatt.com/v2.0
    label: OpenStack Auth URL
    type: string

  domain:
    description: Wildcarded domain, ex example.com must have a *.example.com DNS entry
    default: mycloudmanager
    label: Cloud DNS
    type: string

  flavor_master:
    default: n1.cw.standard-4
    description: Flavor to use for the deployed instance
    type: string
    label: Master Instance Type (Flavor)
    constraints:
      - allowed_values:
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16

  flavor_node:
    default: n1.cw.standard-4
    description: Flavor to use for the deployed instance
    type: string
    label: Node Instance Type (Flavor)
    constraints:
      - allowed_values:
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16


  volume_size:
    default: 20
    label: Backup Volume Size
    description: Size of Volume for Toolbox Storage (Gigabytes)
    type: number
    constraints:
      - range: { min: 20, max: 10000 }
        description: Volume must be at least 10 gigabytes

  volume_type:
    default: standard
    label: Backup Volume Type
    description: Performance flavor of the linked Volume for DevKit Storage
    type: string
    constraints:
      - allowed_values:
          - standard
          - performant

  node_count:
    default: 1
    label: Node Count
    description: Additional node counts
    type: number
    constraints:
      - range: { min: 1, max: 3 }

resources:

  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.0.0/16
      allocation_pools:
        - { start: 10.0.1.100, end: 10.0.1.199 }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: "public"

  toolbox_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, remote_ip_prefix : 10.0.0.0/16, protocol: TCP, port_range_min: 1, port_range_max: 65535 }
        - { direction: ingress, remote_ip_prefix : 10.0.0.0/16, protocol: UDP, port_range_min: 1, port_range_max: 65535 }
        - { direction: ingress, remote_ip_prefix : 0.0.0.0/0, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, remote_ip_prefix : 0.0.0.0/0, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, remote_ip_prefix : 0.0.0.0/0, protocol: TCP, port_range_min: 1723, port_range_max: 1723 }
        - { direction: ingress, remote_ip_prefix : 0.0.0.0/0, protocol: 47 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  vpn_username:
    type: OS::Heat::RandomString
    properties:
      length: 10

  vpn_password:
    type: OS::Heat::RandomString
    properties:
      length: 10

  masters:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: http://storage.fr1.cloudwatt.net:8080/v1/AUTH_772be1ffb32e42a28ac8e0205c0b0b90/toolbox/kube-master.heat.yaml
        properties:
          nodename:
            str_replace:
              template: $stack-master-%index%
              params:
                $stack: { get_param: 'OS::stack_name' }
          domain: { get_param: domain }
          subnet: { get_resource: subnet }
          security_group: { get_resource: security_group }
          network: { get_resource: network }
          keypair_name: { get_param: keypair_name }
          flavor_name: { get_param: flavor_master }
          volume_size: { get_param: volume_size }
          volume_type: { get_param: volume_type }
          os_username: { get_param: os_username }
          os_password: { get_param: os_password }
          os_tenant: { get_param: os_tenant }
          os_auth: { get_param: os_auth }
          floating_ip: { get_resource: floating_ip }
          public_ip: { get_attr: [floating_ip, floating_ip_address] }
          vpn_username: { get_resource: vpn_username }
          vpn_password: { get_resource: vpn_password }

  nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: node_count }
      resource_def:
        type: http://storage.fr1.cloudwatt.net:8080/v1/AUTH_772be1ffb32e42a28ac8e0205c0b0b90/toolbox/kube-node.heat.yaml
        properties:
          domain: { get_param: domain }
          master: 10.0.1.254
          subnet: { get_resource: subnet }
          nodeip: 10.0.1.1%index%
          security_group: { get_resource: security_group }
          volume_size: { get_param: volume_size }
          volume_type: { get_param: volume_type }
          network: { get_resource: network }
          nodename:
            str_replace:
              template: $stack-node-%index%
              params:
                $stack: { get_param: 'OS::stack_name' }
          keypair_name: { get_param: keypair_name }
          flavor_name: { get_param: flavor_node }

outputs:
  public_ip:
    description: VPN IP
    value: { get_attr: [floating_ip, floating_ip_address] }
  vpn_username:
    description: VPN Username
    value: { get_resource: vpn_username }
  vpn_password:
    description: VPN Password
    value: { get_resource: vpn_password }